Set proper exit codes and better messages
127 is "command not found", which is what would be returned from the attempts to run the tools later in the script

diff --git a/script/setup/bower b/script/setup/bower
--- a/script/setup/bower
+++ b/script/setup/bower
@@ -2,8 +2,8 @@
 set -e
 
 if [ -z "$(which bower)" ]; then
-  echo "bower is required." >&2
-  exit 1
+  echo "A local bower installation is required for bower development." >&2
+  exit 127
 fi
 
 # setup test fixtures
diff --git a/script/setup/bundler b/script/setup/bundler
--- a/script/setup/bundler
+++ b/script/setup/bundler
@@ -2,8 +2,8 @@
 set -e
 
 if [ -z "$(which bundler)" ]; then
-  echo "bundler is required." >&2
-  exit 1
+  echo "A local bundler instalation is required for bundler development." >&2
+  exit 127
 fi
 
 # setup test fixtures
diff --git a/script/setup/cabal b/script/setup/cabal
--- a/script/setup/cabal
+++ b/script/setup/cabal
@@ -2,8 +2,8 @@
 set -e
 
 if [ -z "$(which cabal)" ]; then
-  echo "Cabal is required." >&2
-  exit 1
+  echo "A local cabal installation is required for cabal development." >&2
+  exit 127
 fi
 
 # setup test fixtures
diff --git a/script/setup/go b/script/setup/go
--- a/script/setup/go
+++ b/script/setup/go
@@ -2,8 +2,8 @@
 set -e
 
 if [ -z "$(which go)" ]; then
-  echo "The Go runtime environment is required." >&2
-  exit 1
+  echo "A local Go installation is required for go development." >&2
+  exit 127
 fi
 
 # setup test fixtures
diff --git a/script/setup/npm b/script/setup/npm
--- a/script/setup/npm
+++ b/script/setup/npm
@@ -2,8 +2,8 @@
 set -e
 
 if [ -z "$(which npm)" ]; then
-  echo "npm is required." >&2
-  exit 1
+  echo "A local npm installation is required for npm development." >&2
+  exit 127
 fi
 
 # setup test fixtures
